
name: My-First-Ci-CD-Yaml
on:
  workflow_dispatch: 
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the code
        run: echo " code cloned "

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: building the code
        run: echo " code bulded"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: code testing in bg
        run: echo "code was tested"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: code is deploying
        run: echo " code deployed"
      - name: Installing ruff linter  
        run: pip install ruff

        

        

        
     

      
      

  
      
