name: My First DevOps Pipeline

# Trigger: Jab bhi main branch par code push ho
on:
  push:
    branches: [ main ]

jobs:
  test-and-greet:
    runs-on: ubuntu-latest

    steps:
      # Step A: GitHub hamara code is temporary virtual machine par download karega
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      # Step B: DevOps message print karna
      - name: Run Greeting Script
        run: |
          echo "Hello DevOps Engineer Ramzan!"
          echo "Congratulations, your first pipeline is executing perfectly!"

      # Step C: Machine ka status check karna
      - name: Verify Environment Details
        run: |
          echo "Current Date and Time on Runner:"
          date
          echo "Operating System Version:"
          uname -a
